# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Emotion' do
    pod 'Google-Mobile-Ads-SDK', '~> 7.7'
end

rn